### ISSUE TITLE
Feature: CRUD Functionality

### ISSUE THREAD

**Issue by m0nae** [amonae/bookit-app#2]
# Epic Title

Feature: CRUD Functionality

## Epic Description

Add CRUD functionality to the BookIt app. Allow users to create books, view books, delete books, and edit book information.

## Task List

- [x] [Display books](#3 )
  - [x] [Create book display layout](#3)
- [x] [Add "add book" functionality](#4 )
- [x] [Add "delete book" functionality](#5 )
- [x] [Add local storage functionality](#6)

(I also have plans on adding a "rating" system and "currently reading/read/want to read" status options)
- [ ] Create sorting functionality (based on rating, status, alphabetical, etc)
